#!/bin/bash
# (c) 2014 Bernd Wachter <bwachter@lart.info>
# License: GPLv2

for i in `find $(pwd) -path '*/.git/config'`; do
    GITDIR=`echo $i | sed 's,.git/config$,,'`
    cd $GITDIR && git pull --ff-only
done
