#!/bin/sh
# (c) 2014 Bernd Wachter <bwachter@lart.info>
# License: GPLv2

TAG=$1
BRANCH=origin

if [ -z "$TAG" ]; then
    echo "Usage: git rmtag <tag>"
    exit 1
fi

git tag -d $TAG
git push $BRANCH :refs/tags/$TAG
